name: CI

on:
  push:
    branches: [ main, work/orodigitale-local ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run API smoke test (ci-check)
        env:
          TEST_TOKEN: ''
          API_URL: 'http://localhost:3001/api/chat'
        run: |
          # start the server in background and run the smoke test
          node server.js &
          SERVER_PID=$!
          # give server time to start
          sleep 3
          npm run ci-check
          kill $SERVER_PID || true

      - name: Show built files
        run: ls -la dist || echo 'no dist'
